
export const userInputs = [
    {
      id: 1,
      label: "Họ Tên",
      name:"fullName",
      type: "text",
      placeholder: "Nguyễn Văn A",
    },
    {
      id: 2,
      label: "Email",
      name:"email",
      type: "text",
      placeholder: "nva@gmail.com",
    },
    {
      id: 3,
      label: "Phone",
      name:"phone",
      type: "text",
      placeholder: "0388685866",
    },
    {
      id: 4,
      label: "password",
      name:"password",
      type: "text",
      placeholder: "secr",
    },
    {
      id: 5,
      label: "confirmPassword",
      name:"confirmPassword",
      type: "text",
      placeholder: "Tai pv",
    },
    {
      id: 6,
      label: "role",
      name:"role",
      type: "text",
      placeholder: "admin",
    },
    {
      id: 7,
      label: "gender",
      name:"gender",
      type: "text",
      placeholder: "male",
    },
    {
      id: 8,
      label: "avatar",
      name:"avatar",
      type: "text",
      placeholder: "http://res.cloudinary.com/dlspsidpj/image/upload/v1679301202/test/hmrhf2youvp90lganosb.png",
    },
    {
      id: 9,
      label: "status",
      name:"status",
      type: "text",
      placeholder: "active",
    },
    {
      id: 10,
      label: "contact",
      name:"contact",
      type: "text",
      placeholder: "Me trì",
    },
    {
      id: 11,
      label: "dobDay",
      name:"dobDay",
      type: "text",
      placeholder: 1,
    },
    {
      id: 12,
      label: "dobMonth",
      name:"dobMonth",
      type: "text",
      placeholder: 1,
    },
    {
      id: 13,
      label: "dobYear",
      name:"dobYear",
      type: "text",
      placeholder: 1,
    },
    {
      id: 14,
      label: "merchantPhone",
      name:"merchantPhone",
      type: "text",
      placeholder: "0388685866",
    },
    {
      id: 15,
      label: "merchantName",
      name:"merchantName",
      type: "text",
      placeholder: "merchantName",
    },
    {
      id: 16,
      label: "merchantAddress",
      name:"merchantAddress",
      type: "text",
      placeholder: "merchantAddress",
    },
    {
      id: 17,
      label: "cityCode",
      name:"cityCode",
      type: "text",
      placeholder: "cityCode",
    },
    {
      id: 18,
      label: "districtCode",
      name:"districtCode",
      type: "text",
      placeholder: "districtCode",
    },
    {
      id: 19,
      label: "wardCode",
      name:"wardCode",
      type: "text",
      placeholder: "wardCode",
    },
    {
      id: 20,
      label: "merchantSubdomain",
      name:"merchantSubdomain",
      type: "text",
      placeholder: "merchantSubdomain",
    },
  ];
  
  export const productInputs = [
    {
      id: 1,
      label: "Title",
      type: "text",
      placeholder: "Apple Macbook Pro",
    },
    {
      id: 2,
      label: "Description",
      type: "text",
      placeholder: "Description",
    },
    {
      id: 3,
      label: "Category",
      type: "text",
      placeholder: "Computers",
    },
    {
      id: 4,
      label: "Price",
      type: "text",
      placeholder: "100",
    },
    {
      id: 5,
      label: "Stock",
      type: "text",
      placeholder: "in stock",
    },
  ];
  